# Generated by Django 5.0.6 on 2024-07-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levels',
            old_name='_class',
            new_name='_class_id',
        ),
    ]
