# Generated by Django 5.0.6 on 2024-07-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename__class_id_levels__class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Classe',
        ),
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.RenameModel(
            old_name='TeacherClasses',
            new_name='TeacherClasse',
        ),
        migrations.AlterModelTable(
            name='classe',
            table='Classe',
        ),
        migrations.AlterModelTable(
            name='classpackclasse',
            table='Class_Pack_Classe',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='Enrollment',
        ),
        migrations.AlterModelTable(
            name='level',
            table='Level',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teacher',
        ),
        migrations.AlterModelTable(
            name='teacherclasse',
            table='Teacher_Classe',
        ),
    ]
